apiVersion: apps/v1
kind: Deployment
metadata:
  name: loan-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: loan-app
  template:
    metadata:
      labels:
        app: loan-app
    spec:
      containers:
        - name: loan-app
          image: loan-app:v1
          ports:
            - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: loan-app-service
spec:
  selector:
    app: loan-app
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
  type: NodePort
