apiVersion: v1
kind: ConfigMap
metadata:
  name: logstash-config
data:
  logstash.conf: |
    input {
      beats {
        port => 5044
      }
    }
    filter {
      if [source] == "loan-application-service" {
        mutate {
          add_field => { "service" => "loan-application-service" }
        }
      } else if [source] == "credit-score-service" {
        mutate {
          add_field => { "service" => "credit-score-service" }
        }
      }
    }
    output {
      elasticsearch {
        hosts => ["http://elasticsearch:9200"]
        index => "loan-credit-logs"
      }
      stdout { codec => rubydebug }
    }
